project:
  type: website
  output-dir: ../docs

website:
  title: "biomAid"
  navbar:
    left:
      - text: "Vignettes"
        menu:
          - text: "Wald Tests on Fixed-Effect Contrasts"
            href: waldTest.html
          - text: "Multivariate Random Regression"
            href: randomRegress.html
          - text: "Multivariate Fixed-Effects Regression"
            href: fixedRegress.html
          - text: "Extracting and Padding Field Trial Layouts"
            href: padTrial.html
          - text: "Multiple Comparison Criteria"
            href: compare.html

format:
  html:
    theme: litera
    css: custom.css
    toc: true
    toc-depth: 3
    toc-location: left
    number-sections: false
    smooth-scroll: true
    embed-resources: true
    code-fold: false
    highlight-style: github

execute:
  freeze: auto
